yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текстовое поле'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Вставьте картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Комментарий',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария.',
        help_text='Напишите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата добавления.',
        auto_now_add=True
    )

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Последователь: '{self.user}', автор: '{self.author}'"

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

POSTS_COUNT = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = (request.user.is_authenticated
                 and request.user.username != username
                 and Follow.objects.filter(user=request.user, author=author))
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user)
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(post)
    if request.user != post.author:
        return redirect(post)
    form = PostForm(instance=post)
    context = {
        'is_edit': True,
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(post)


@login_required
def follow_index(request):
    posts_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(
        request,
        'posts/follow.html',
        context
    )


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
        return redirect(
            'posts:profile',
            username=username
        )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.filter(user=user, author__username=username).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактирование поста
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
  {% if is_edit %}
    {% include "includes/form.html" with entrance="Редактировать пост" button="Редактировать" %}
  {% else %}
    {% include "includes/form.html" with entrance="Добавить запись" button="Сохранить" %}
  {% endif %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Все посты авторов, на которых Вы подписаны{% endblock %}
{% block content %}
{% load cache %}
{% include 'posts/includes/switcher.html' with index=True follow=True %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<h1>{{ group.title }}</h1>
  <article>
    {% for post in page_obj %}
    <ul>
      <p>{{ group.description }}</p>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}      
    <p>
      {{ post.text }}
    </p> 
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page page%}
{% include 'posts/includes/switcher.html' with index=True follow=True %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
<aside class="col-12 col-md-3">
   <ul class="list-group list-group-flush">
      <li class="list-group-item">
         Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
      {% if post.group %}    
      <li class="list-group-item">
         Группа: {{ post.group.title }}
         <a href="{% url 'posts:group_list' post.group.slug %}">
         все записи группы
         </a>
      </li>
      {% endif %}
      <li class="list-group-item">
         Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
         Всего постов автора:  <span >{{ post.author.posts.count }}</span>
      </li>
      <li class="list-group-item">
         <a href="{% url 'posts:profile' post.author %}">
         все посты пользователя
         </a>
      </li>
   </ul>
</aside>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<article class="col-12 col-md-9">
   <p>{{ post.text }}</p>
</article>
<div class="d-flex justify-content-end">
   {% if request.user == post.author %}
   <button type="submit">
   <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}"> Редактировать пост </a>
   </button>
   {% endif %}
</div>
{% if user.is_authenticated %}
<div class="card my-4">
   <h5 class="card-header">Добавить комментарий:</h5>
   <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}      
      <div class="form-group mb-2">
         {{ form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
   </div>
</div>
{% endif %}
{% for comment in comments %}
   <div class="media mb-4">
      <div class="media-body">
      <h5 class="mt-0">
         <a href="{% url 'posts:profile' comment.author.username %}">
         {{ comment.author.username }}
         </a>
      </h5>
         <p>
         {{ comment.text }}
         </p>
      </div>
   </div>
{% endfor %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<title>Профайл пользователя {{ author.get_full_name }}</title>
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
    href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
</div>   
<article>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }} 
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text }} 
  </p>
  <a href={% url 'posts:post_detail' post.pk %}>подробная информация</a>
</article>
{% if post.group %}       
<a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>
{% endif %}        
{% if not forloop.last %}<hr>{% endif %}
{% include 'posts/includes/paginator.html' %} 
{% endfor %}
{% endblock %}